version: "3.8"
services:
  backend:
    image: docker.pkg.github.com/leonschbbht/feedibus/database:latest
    container_name: database
    expose:
      - 5432
  master:
    image: docker.pkg.github.com/leonschbbht/feedibus/master:latest
    container_name: node-master
    ports:
    - 8081:3000