---
# add docker
- name: Add docker repository Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
- name: add compose templates
  template:
    src: templates/docker-compose.yml
    dest: /opt/docker-compose.yml
- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: latest