---
- name: Prepare Docker environment for automated deployment
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker
    - certbot
    - initial-script