name: Auto Assign milestoned Issues to sprint Backlog
on:
  issues:
    types: [milestoned]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Sprint Backlog
    steps:
    - uses: alex-page/github-project-automation-plus@v0.3.0
      with:
        project: 'Scrum Board'
        column: 'Sprint Backlog'
        repo-token: ${{ secrets.GITHUB_TOKEN }}